### ISSUE TITLE
Super optimization technique

### ISSUE THREAD

**Issue by StijnPaladin** [SanderHageman/advent_of_code_2020#1]
https://github.com/SanderHageman/advent_of_code_2020/blob/f1f46b0dfdd8d17eccd8715cecea65b16cb737d6/src/day2.rs#L37

`(l == self.char || h == self.char) && l != h` can be optimized to `(l == self.char) != (h ==self.char)`

**Comment by SanderHageman** [comment]
I wouldn't say 'more obscure' means the same as 'optimized', but if you say so it must be right 🤷

**Comment by SanderHageman** [comment]
Hello Stijn,
Thank you for your input. We have taken your issue very seriously and are considering implementing your proposed resolution.

Kind regards,
Sander
-------- Original Message --------

**Comment by SanderHageman** [comment]
Reopening; this is too important to let go
